services:
  app:
    container_name: app
    user: "node"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /workspace/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
